version: '3'
services: 
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports: 
        - 27017:27017
    volumes: 
        - ./data:/data
  movieflix:
    image: movieflix
    restart: always
    container_name: movieFlix
    ports: 
        - 5000:5000
    environment: 
        - "MONGO_HOSTNAME=mongodb"